version: "3.9"  # specify version for best compatibility

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Iamaprogrammer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  db_data:
    driver: local
  keycloak_data:
    driver: local